#!/bin/bash
#
# $Id$
#
#
# Create the run environment for the VAP software. Requires that the
# bestiary of environmental variables be defined.
#
# $Log$
# Revision 1.5  2003/01/31 01:09:03  vapdev
# Some last minute touchups!
#
# Revision 1.4  2003/01/30 22:55:37  vapdev
# GOES/GMS5 work directories
#
# Revision 1.3  2003/01/30 19:56:59  vapdev
# some other nigglies
#
# Revision 1.2  2003/01/30 19:41:55  vapdev
# bash script error
#
# Revision 1.1  2003/01/30 18:04:52  vapdev
# Moved create_run_environment to scr
#
# Revision 1.2  2003/01/29 00:10:02  vapdev
# Continuing work
#
# Revision 1.1  2003/01/27 16:15:03  vapdev
# Initial revision
#
#
#

# It's assumed that all the software directories are created in during
# `cvs export`. At the moment the perl script `make_release' run cvs
# export and repositions the software so that, for instance, all the
# IDL code is in one directory, instead several levels of directory tree.
#

# --- Work directories
echo making working directories
mkdir -p $VAP_OPS_ANIM/{NEPAC,NPAC,NWATL,PACHURR,ATLHURR,INDIAN,NWPAC}
mkdir -p $VAP_OPS_OVERLAY
mkdir -p $VAP_OPS_TS_OVERLAY
mkdir -p $VAP_OPS_TMPFILES
mkdir -p $VAP_OPS_LOGFILES

# --- Goes and GMS stuff
echo GMS/GOES working directories
mkdir -p $VAP_GOES_TOP/goes{8,10}/ir{1,2,3,4}
mkdir -p $VAP_GOES_TOP/goes{8,10}/vis
mkdir -p $VAP_GOES_GRIDDED_TOP/goes{8,10}/ir{1,2,3,4}
mkdir -p $VAP_GOES_GRIDDED_TOP/goes{8,10}/vis
mkdir -p $VAP_GMS_TOP/ir{1,2,3}
mkdir -p $VAP_GMS_TOP/vis
mkdir -p $VAP_GMS_TOP/{grid,grida}

# --- WWW directories

# these directories have to be group/world readible and searchible, so
# save the umask, then set it to 022 and set the directories
# permission to 0755.

saveumask=`umask`
umask 022;
echo WWW top
if [ ! -d $VAP_WWW_TOP ]; then
    mkdir  -p $VAP_WWW_TOP
fi

echo overlay archive
if [ ! -d $VAP_OVERLAY_ARCHIVE ]; then 
    mkdir -m 0755 -p $VAP_OVERLAY_ARCHIVE
fi

echo TS archives
if [ ! -d $VAP_TS_ARCHIVE ]; then 
    mkdir -m 0755 -p $VAP_TS_ARCHIVE
fi

echo anim archive
if [ ! -d $VAP_ANIM_ARCHIVE ]; then 
    mkdir -m 0755 -p $VAP_ANIM_ARCHIVE
fi

chmod -R u=rwx,go=rx $VAP_WWW_TOP
umask `echo $saveumask`

