#!/bin/bash
#
# $Id$
#
#
# Create the run environment for the VAP software. Requires that the
# bestiary of environmental variables be defined.
#
# $Log$
# Revision 1.1  2003/01/27 16:15:03  vapdev
# Initial revision
#
#
#

mkdir -p $VAP_SFTWR_TOP
mkdir -p $VAP_SFTWR_SRC
mkdir -p $VAP_SFTWR_SCR
mkdir -p $VAP_SFTWR_PERL
mkdir -p $VAP_SFTWR_IDL
mkdir -p $VAP_SFTWR_IDL_EXTERNAL
mkdir -p $VAP_SFTWR_IDL_COMMON
mkdir -p $VAP_LIBRARY
mkdir -p $VAP_RESOURCES
mkdir -p $VAP_COLORTABLES
mkdir -p $VAP_BITMAPS

# --- Work directories
mkdir -p $VAP_OPS_ANIM
mkdir -p $VAP_OPS_OVERLAY
mkdir -p $VAP_OPS_TS_OVERLAY
mkdir -p $VAP_OPS_TMPFILES
mkdir -p $VAP_OPS_LOGFILES

# --- Goes and GMS stuff
mkdir -p $VAP_GOES_TOP
mkdir -p $VAP_GOES_GRIDDED_TOP
mkdir -p $VAP_GMS_TOP

# --- WWW directories
mkdir -p $VAP_WWW_TOP
mkdir -p $VAP_OVERLAY_ARCHIVE
mkdir -p $VAP_TS_ARCHIVE
mkdir -p $VAP_ANIM_ARCHIVE


