#!/usr/bin/perl
#
# $Id$
#
# Goes through the FTP site and puts any new links in that need it.
#
# Modifications:
#
# $Log$
# Revision 1.1  2000/02/10 17:39:03  vapuser
# Initial revision
#
#
#

use vap_perl;
use Cwd 'chdir';
local(%mark);
%mark=();
($name,$passwd,$uid,$gid,$quota,$comment,$gcos,$dir,$shell)=getpwnam('ftp');

chdir $dir || die "Can't cd to ftp home dir $dir\n";


# ---------- do the QuikSCAT data --------------------------- #

opendir(DATA,$VAP_WINDS) || die "Couldn't open archive dir $VAP_WINDS\n";
@arc_files = grep( /QS\d{8,8}\.S\d{4,4}\.E\d{4,4}$/, readdir(DATA) );
opendir(QUIKSCAT,"pub/QuikSCAT/data") || 
    die "Couldn't open dir pub/QuikSCAT/data\n";
@ftp_files = grep( s/(QS\d{8,8}\.S\d{4,4}\.E\d{4,4})/$1/, readdir(QUIKSCAT) );

grep($mark{$_}++,@ftp_files);
@diff=grep(!$mark{$_},@arc_files);

foreach $f (@diff) {
  $oldfile="$VAP_WINDS/$f";
  $newfile="$dir/pub/QuikSCAT/data/$f";
  print "Linking $oldfile to $newfile\n";
  link( $oldfile, $newfile ) || print "Couldn't link $oldfile to $newfile\n";
}
exit;







